name: upload-storybook.yml
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - .

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install
      - run: yarn build-storybook
      - name: Setup target directory
        id: setdir
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "::set-output name=target_dir::storybook"
          else
            echo "::set-output name=target_dir::storybook/${{ github.ref_name }}"
          fi
      - run: |
          mkdir -p ${{ steps.setdir.outputs.target_dir }}
          cp -R storybook-static/* ${{ steps.setdir.outputs.target_dir }}/
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ${{ steps.setdir.outputs.target_dir }}
          # TODO remove files 
          # WHY have 1G space for ~400 instances of site branches (~2.5MB)
          # WHEN TELFE-699
          keep_files: true
